<?php
//vc_remove_element( "vc_accordion" );
add_action( 'vc_before_init', 'imedica_accordion_init' );
function imedica_accordion_init() {
	if ( class_exists( 'WPBakeryShortCode' ) ) {
		class WPBakeryShortCode_imedica_accordion extends WPBakeryShortCode {
		}
	}
	vc_map( array(
		'name' => __( 'iMedica Accordion', 'imedica' ),
		'base' => 'vc_accordion',
		'show_settings_on_create' => false,
		'is_container' => true,
		'icon' => 'icon-wpb-ui-accordion',
		'category' => __( 'iMedica', 'imedica' ),
		'description' => __( 'Collapsible content panels', 'imedica' ),
		'admin_enqueue_css' => array(get_template_directory_uri().'/vc_templates/css/imd-vc-accordion-admin.css'),
		'params' => array(
			array(
				'type' => 'textfield',
				'heading' => __( 'Widget title1', 'imedica' ),
				'param_name' => 'title',
				'description' => __( 'Enter text used as widget title (Note: located above content element).', 'imedica' ),
			),
			array(
				'type' => 'textfield',
				'heading' => __( 'Active section', 'imedica' ),
				'param_name' => 'active_tab',
				'value' => 1,
				'description' => __( 'Enter section number to be active on load or enter "false" to collapse all sections.', 'imedica' ),
			),
			array(
				'type' => 'checkbox',
				'heading' => __( 'Allow collapse all sections?', 'imedica' ),
				'param_name' => 'collapsible',
				'description' => __( 'If checked, it is allowed to collapse all sections.', 'imedica' ),
				'value' => array( __( 'Yes', 'imedica' ) => 'yes' ),
			),
			array(
				'type' => 'checkbox',
				'heading' => __( 'Disable keyboard interactions?', 'imedica' ),
				'param_name' => 'disable_keyboard',
				'description' => __( 'If checked, disables keyboard arrow interactions (Keys: Left, Up, Right, Down, Space).', 'imedica' ),
				'value' => array( __( 'Yes', 'imedica' ) => 'yes' ),
			),
			array(
				'type' => 'textfield',
				'heading' => __( 'Extra class name', 'imedica' ),
				'param_name' => 'el_class',
				'description' => __( 'Style particular content element differently - add a class name and refer to it in custom CSS.', 'imedica' ),
			),
			array(
				"type"       => "dropdown",
				"class"      => "",
				"heading"    => __( "Select Colors:", "imedica" ),
				"param_name" => "custom_colors",
				"value"      => array(
					"Simplify" => "on",
					"Custom"   => "off",
				),
				"group"      => "Color Settings",
			), 
			array(
				"type"             => "ult_param_heading",
				"param_name"       => "theme_colors",
				"text"             => __( "Theme Color", "imedica" ),
				"value"            => "",
				"class"            => "",
				"group"            => "Color Settings",
				'edit_field_class' => 'ult-param-heading-wrapper vc_column vc_col-sm-12',
				"dependency"       => Array( "element" => "custom_colors", "value" => "on" ),
			), 
			array(
				"type"        => "colorpicker",
				"class"       => "",
				"heading"     => __( "Theme Color", "imedica" ),
				"param_name"  => "theme_color",
				"description" => __( "We will apply hover/active colors as per theme.!", "imedica" ),
				"group"       => "Color Settings",
				"dependency"  => Array( "element" => "custom_colors", "value" => "on" ),
			), 
			array(
				"type"             => "ult_param_heading",
				"param_name"       => "default_tab_colors",
				"text"             => __( "Default Tab - Colors", "imedica" ),
				"value"            => "",
				"class"            => "",
				"group"            => "Color Settings",
				'edit_field_class' => 'ult-param-heading-wrapper vc_column vc_col-sm-12',
				"dependency"       => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Text", "imedica" ),
				"param_name" => "text_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			),
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Icon", "imedica" ),
				"param_name" => "icon_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Background", "imedica" ),
				"param_name" => "bg_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"             => "ult_param_heading",
				"param_name"       => "hover_tab_colors",
				"text"             => __( "Hover Tab - Colors", "ultimate" ),
				"value"            => "",
				"class"            => "",
				"group"            => "Color Settings",
				'edit_field_class' => 'ult-param-heading-wrapper vc_column vc_col-sm-12',
				"dependency"       => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Text", "imedica" ),
				"param_name" => "text_hover_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Icon", "imedica" ),
				"param_name" => "icon_hover_color",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
				"group"      => "Color Settings",
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Icon Background", "imedica" ),
				"param_name" => "icon_bg_hover_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"             => "ult_param_heading",
				"param_name"       => "active_tab_colors",
				"text"             => __( "Active Tab - Colors", "ultimate" ),
				"value"            => "",
				"class"            => "",
				"group"            => "Color Settings",
				'edit_field_class' => 'ult-param-heading-wrapper vc_column vc_col-sm-12',
				"dependency"       => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Text", "imedica" ),
				"param_name" => "text_active_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Icon", "imedica" ),
				"param_name" => "icon_active_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"       => "colorpicker",
				"class"      => "",
				"heading"    => __( "Background", "imedica" ),
				"param_name" => "bg_active_color",
				"group"      => "Color Settings",
				"dependency" => Array( "element" => "custom_colors", "value" => "off" ),
			), 
			array(
				"type"             => "ult_param_heading",
				"param_name"       => "title_typography_heading",
				"text"             => __( "Title Settings", "ultimate" ),
				"value"            => "",
				"class"            => "",
				"group"            => "Typography",
				'edit_field_class' => 'ult-param-heading-wrapper vc_column vc_col-sm-12',
			), 
			array(
				"type"       => "ultimate_google_fonts",
				"heading"    => __( "Font Family", "imedica" ),
				"param_name" => "title_font",
				"description" => __( "Select the font of your choice. You can <a target='_blank' href='" . admin_url( 'admin.php?page=bsf-google-font-manager' ) . "'>add new in the collection here</a>.", "imedica" ),
				"value"      => "",
				"group"      => "Typography",
			), 
			array(
				"type"       => "ultimate_google_fonts_style",
				"heading"    => __( "Font Style", "imedica" ),
				"param_name" => "title_font_style",
				"value"      => "",
				"group"      => "Typography",
			), 
			array(
				"type"             => "number",
				"param_name"       => "title_font_size",
				"heading"          => __( "Font size", "imedica" ),
				"value"            => "",
				"suffix"           => "px",
				"min"              => 10,
				"group"            => "Typography",
				"edit_field_class" => "vc_col-sm-12 ultimate-admin-field-top-margin",
			), 
			array(
				"type"             => "number",
				"param_name"       => "title_font_line_height",
				"heading"          => __( "Font Line Height", "imedica" ),
				"value"            => "",
				"suffix"           => "px",
				"min"              => 10,
				"group"            => "Typography",
				"edit_field_class" => "vc_col-sm-12 ultimate-admin-field-top-margin",
			),
			array(
				'type' => 'css_editor',
				'heading' => __( 'CSS', 'imedica' ),
				'param_name' => 'css_wrapper',
				'edit_field_class' => 'vc_col-sm-12 vc_column no-vc-background no-vc-border creative_link_css_editor',
				"group"      => __( "Design", "imedica" ),
			),
		),
		'custom_markup' => ' <div class="wpb_accordion_holder wpb_holder clearfix vc_container_for_children"> 
				%content% 
			</div>
			<div class="tab_controls">
			    <a class="add_tab" title="' . __( 'Add section', 'imedica' ) . '"><span class="vc_icon"></span> <span class="tab-label">' . __( 'Add section', 'imedica' ) . '</span></a>
			</div>
			',
		'default_content' => '
		    [vc_accordion_tab title="' . __( 'Section 1', 'imedica' ) . '"][/vc_accordion_tab]
		    [vc_accordion_tab title="' . __( 'Section 2', 'imedica' ) . '"][/vc_accordion_tab]
		',
		'js_view' => 'VcAccordionView',
	) );
}