<?php
add_action( 'widgets_init', 'flickr_load_widgets' );
function flickr_load_widgets() {
	register_widget( 'iMedica_Flickr_Widget' );
}
class iMedica_Flickr_Widget extends WP_Widget {
	function __construct() {
		$widget_ops  = array(
			'classname'   => 'flickr',
			'description' => __( 'The most recent photos from flickr.', "imedica" )
		);
		$control_ops = array( 'id_base' => 'flickr-widget' );
		parent::__construct( 'flickr-widget', __( 'iMedica: Flickr', "imedica" ), $widget_ops, $control_ops );
	}
	function widget( $args, $instance ) {
		extract( $args );
		$title       = apply_filters( 'widget_title', $instance['title'] );
		$screen_name = $instance['screen_name'];
		$number      = $instance['number'];
		$api         = $instance['api'];
		if ( empty( $api ) ) {
			$api = 'ab275033e7d40ec70853634184e8f2fe';
		}
		echo $before_widget;
		if ( $title ) {
			echo $before_title . $title . $after_title;
		}
		if ( $screen_name && $number && $api ) { ?>
			<script type="text/javascript">
				function jsonFlickrApi(rsp) {
					if (rsp.stat != "ok") {
						// If this executes, something broke!
						return;
					}
					//variable "s" is going to contain
					//all the markup that is generated by the loop below
					var s = "";
					//this loop runs through every item and creates HTML
					for (var i = 0; i < rsp.photos.photo.length; i++) {
						photo = rsp.photos.photo[i];
						//notice that "t.jpg" is where you change the
						//size of the image
						t_url = "http://farm" + photo.farm +
						".static.flickr.com/" + photo.server + "/" +
						photo.id + "_" + photo.secret + "_" + "s.jpg";
						p_url = "http://www.flickr.com/photos/" +
						photo.owner + "/" + photo.id;
						s += '<div class="flickr_badge_image"><a href="' + p_url + '">' + '<img width="75" height="75" alt="' +
						photo.title + '"src="' + t_url + '"/>' + '</a></div>';
					}
					document.write(s);
				}
			</script>
			<script type="text/javascript"
			        src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;user_id=<?php echo esc_attr($screen_name); ?>&amp;api_key=<?php echo esc_attr($api); ?>&amp;media=photos&amp;per_page=<?php echo esc_attr($number); ?>&amp;privacy_filter=1"></script>
			<script type="text/javascript"
			        src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;group_id=<?php echo esc_attr($screen_name); ?>&amp;api_key=<?php echo esc_attr($api); ?>&amp;media=photos&amp;per_page=<?php echo esc_attr($number); ?>&amp;privacy_filter=1"></script>
		<?php }
		echo $after_widget;
	}
	function update( $new_instance, $old_instance ) {
		$instance                = $old_instance;
		$instance['title']       = strip_tags( $new_instance['title'] );
		$instance['screen_name'] = $new_instance['screen_name'];
		$instance['number']      = $new_instance['number'];
		$instance['api']         = $new_instance['api'];
		return $instance;
	}
	function form( $instance ) {
		$defaults = array(
			'title'       => __( 'Photos from Flickr', "imedica" ),
			'screen_name' => '',
			'number'      => 6,
			'api'         => 'c9d2c2fda03a2ff487cb4769dc0781ea'
		);
		$instance = wp_parse_args( (array) $instance, $defaults ); ?>
		<p>
			<label for="<?php echo esc_attr($this->get_field_id( 'title' )); ?>"><?php _e( "Title:", "imedica" ); ?></label>
			<input class="widefat" type="text" id="<?php echo esc_attr($this->get_field_id( 'title' )); ?>"
			       name="<?php echo esc_attr($this->get_field_name( 'title' )); ?>" value="<?php echo esc_attr($instance['title']); ?>"/>
		</p>
		<p>
			<label
				for="<?php echo esc_attr($this->get_field_id( 'screen_name' )); ?>"><?php _e( "Flickr ID(<a href=\"http://idgettr.com/\">Get your flickr ID</a>):", "imedica" ); ?></label>
			<input class="widefat" type="text" id="<?php echo esc_attr($this->get_field_id( 'screen_name' )); ?>"
			       name="<?php echo esc_attr($this->get_field_name( 'screen_name' )); ?>"
			       value="<?php echo esc_attr($instance['screen_name']); ?>"/>
		</p>
		<p>
			<label
				for="<?php echo esc_attr($this->get_field_id( 'number' )); ?>"><?php _e( "Number of photos to show:", "imedica" ); ?></label>
			<input class="widefat" type="text" style="width: 30px;" id="<?php echo esc_attr($this->get_field_id( 'number' )); ?>"
			       name="<?php echo esc_attr($this->get_field_name( 'number' )); ?>" value="<?php echo esc_attr($instance['number']); ?>"/>
		</p>
		<p>
			<label
				for="<?php echo esc_attr($this->get_field_id( 'api' )); ?>"><?php _e( "API key (Use Default or get your own from <a href=\"http://www.flickr.com/services/apps/create/apply\">Flickr APP Garden </a>):", "imedica" ); ?></label>
			<input class="widefat" type="text" id="<?php echo esc_attr($this->get_field_id( 'api' )); ?>"
			       name="<?php echo esc_attr($this->get_field_name( 'api' )); ?>" value="<?php echo esc_attr($instance['api']); ?>"/>
			<small><?php _e( "Default key is:", "imedica" ); ?> ab275033e7d40ec70853634184e8f2fe</small>
		</p>
	<?php
	}
}